### ISSUE TITLE
Selected text color

### ISSUE THREAD

**Issue by blipinsk** [kaushikgopal/san-jose-theme#1]
I don't know if you're planning to keep it as close to the original theme as possible or if you're going to improve it, but I think the selected text color could use some tweaking.

It just looks like a comment:
<img width="664" alt="zrzut ekranu 2018-03-15 o 19 39 57" src="https://user-images.githubusercontent.com/6371716/37484492-f2b11bc8-2888-11e8-9f2d-e9d14c4c6e6b.png">

**Comment by kaushikgopal** [comment]
@blipinsk - oh totally open to adapting to this. Ideas on what would be a better tweak for selected text color? happy to try some tweaks 

(or even better shoot a PR :) )

**Comment by blipinsk** [comment]
@kaushikgopal I think I just needed to get used to it. ~5 months of using it went by and I think I'm fine with this sort of selected text color.

Still my favourite theme.
