### ISSUE TITLE
Preview font

### ISSUE THREAD

**Issue by lednifrolg** [kaushikgopal/san-jose-theme#2]
Hi Kaushik, may i ask you what kind of font you are using in the preview? https://raw.githubusercontent.com/kaushikgopal/san-jose-intellij-theme/master/preview.png

**Comment by erickok** [comment]
IBM Plex

**Comment by kaushikgopal** [comment]
hey @lednifrolg that's right! I use IBM Plex Mono (which is free). I wrote about [my love affair with this font here](https://blog.kaush.co/2018/03/02/my-new-programming-font/).
